on: [push, pull_request]

name: Test-Suite stable macos-latest

jobs:
  CI-stable-macos-latest:
    uses: ./.github/workflows/reuse.yml
    with:
      toolchain: stable
      os: macos-latest
      packages: vtk
      environment_vars: 
